// NOTIFICATION EVENT TYEP

export type NotificationEventType = 
    | 'ORDER ACCEPTED'
    | 'ORDER WORKING ON'
    | 'ORDER READY'
    | 'ORDER SENDED'
    | 'ORDER DELIVERED'
    | 'ORDER CANCELED'
    | 'NEW ORDER'
    | 'ORDER BATCH ASSIGNED'
    | 'ORDER BATCH REASSIGBED'
    | 'ORDER BATCH CANCELED'
    | 'ORDER BATCH PICKED UP'
    | 'ORDER_BATCH_COMPLETED'
    | 'ORDER PIN CODE'
    | 'ORDER TEMPERATURE LOW'
    | 'ORDER TEMPERATURE HIGH'
    | 'ORDER HUMIDITY LOW'
    | 'ORDER HUMIDITY HIGH'
    | 'ORDER BATCH TEMPERATURE LOW'
    | 'ORDER BATCH TEMPERATURE HIGH'
    | 'ORDER BATCH HUMIDITY LOW'
    | 'ORDER BATCH HUMIDITY HIGH'
    | 'ORDER SHOCK'
    | 'ORDER BATCH SHOCK';

export const ORDER_USER_NOTIFICATION_EVENT_TYPE: NotificationEventType[] = [
    'ORDER ACCEPTED',
    'ORDER WORKING ON',
    'ORDER READY',
    'ORDER SENDED',
    'ORDER DELIVERED',
    'ORDER CANCELED',
];

export const ORDER_USER_PIN_CODE_NOTIFICATION_EVENT_TYPE: NotificationEventType[] = [
    'ORDER PIN CODE'
];

export const ORDER_COMPANY_ORDER_NOTIFICATION_EVENT_TYPE: NotificationEventType[] = [
    'NEW ORDER',
    'ORDER DELIVERED'
];

export const ORDER_USER_PARAMS_NOTIFICATION_EVENT_TYPE: NotificationEventType[] = [
    'ORDER TEMPERATURE LOW',
    'ORDER TEMPERATURE HIGH',
    'ORDER HUMIDITY LOW',
    'ORDER HUMIDITY HIGH',
    'ORDER SHOCK'
];

export const ORDER_COMPANY_PARAMS_NOTIFICATION_EVENT_TYPE = ORDER_USER_PARAMS_NOTIFICATION_EVENT_TYPE;

export const ORDER_NOTIFICATION_EVENT_TYPE: NotificationEventType[] = [
    ...ORDER_USER_NOTIFICATION_EVENT_TYPE,
    ...ORDER_USER_PIN_CODE_NOTIFICATION_EVENT_TYPE,
    ...ORDER_COMPANY_ORDER_NOTIFICATION_EVENT_TYPE,
    ...ORDER_USER_PARAMS_NOTIFICATION_EVENT_TYPE
];

export const ORDER_DELIVERY_BATCH_COURIER_ASSIGN_EVENT_TYPE: NotificationEventType[] = [
    'ORDER BATCH ASSIGNED',
    'ORDER BATCH CANCELED',
    'ORDER BATCH REASSIGBED'
];

export const ORDER_DELIVERY_BATCH_COMPANY_STATUS_EVENT_TYPE: NotificationEventType[] = [
    'ORDER BATCH PICKED UP',
    'ORDER_BATCH_COMPLETED'
];

export const ORDER_DELIVERY_BATCH_COURIER_PARAMS_EVENT_TYPE: NotificationEventType[] = [
    'ORDER BATCH TEMPERATURE LOW',
    'ORDER BATCH TEMPERATURE HIGH',
    'ORDER BATCH HUMIDITY LOW',
    'ORDER BATCH HUMIDITY HIGH',
    'ORDER BATCH SHOCK'
];

export const ORDER_DELIVERY_BATCH_COMPANY_PARAMS_EVENT_TYPE = ORDER_DELIVERY_BATCH_COURIER_PARAMS_EVENT_TYPE;

export const ORDER_DELIVERY_BATCH_NOTIFICATION_EVENT_TYPE: NotificationEventType[] = [
    ...ORDER_DELIVERY_BATCH_COURIER_ASSIGN_EVENT_TYPE,
    ...ORDER_DELIVERY_BATCH_COMPANY_STATUS_EVENT_TYPE,
    ...ORDER_DELIVERY_BATCH_COURIER_PARAMS_EVENT_TYPE
];
