export const ACCESS_TOKEN  =   'ARTICLINE-ACCESS-JWT-TOKEN'
export const REFRESH_TOKEN =   'ARTICLINE-REFRESH-JWT-TOKEN'

export const SIDEBAR_ICON_SIZE = 22.5
export const SIDEBAR_SUB_ICON_SIZE = 18.5